### ISSUE TITLE
`start` is not a cli command

### ISSUE THREAD

**Issue by roderik** [c6o/docs#91]
### Summary:

Trying teleport out, and in the guides, it mentions `sudo czctl start` which does not exist in cli 1.1.1. I assume init replaces it.

https://github.com/c6o/docs/blob/ead0f9d50fe09aa3ef46fcf798cafae6d589b450/content/guides/getting-started.md#L20

**Comment by conneryn** [comment]
Thanks so much for raising this issue.  This is one of those _rare_ instances where the documentation actually got **ahead** of the software 😊  

We are preparing to release a new version of the CLI that introduces `czctl start` in favour of `init` (`init` will continue to work for backwards compatibility), but we accidentally released the documentation for this command too early 🤦‍♂️.

We will revert this reference until the next release is actually published (See: https://github.com/c6o/docs/pull/92).  

Thanks again!

**Comment by conneryn** [comment]
Just a quick update to this issue, `czctl start` is now added in the latest CLI version (v1.2.0).
